// Generated by tools/generate_marks.mjs from docs/design/logo. Do not edit:
// `npm run verify` fails when this no longer matches the design source.
//
// The min tier — a line of prose under a ring, with the squiggle broken. It is
// the mark that stays legible small, which is every place a running app shows
// one. Colours are tokens, so it follows the theme and the accent.
export const MARK_MIN_SVG = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\" width=\"24\" height=\"24\" fill=\"none\"><circle cx=\"50\" cy=\"50\" r=\"33\" stroke=\"currentColor\" stroke-width=\"7\" opacity=\"0.3\" fill=\"none\"/><rect x=\"30\" y=\"39.5\" width=\"40\" height=\"6\" rx=\"3\" fill=\"currentColor\" opacity=\"0.58\"/><path d=\"M30.4 55.5 Q32.7 53.1 35 55.5 Q37.3 57.9 39.6 55.5 Q41.9 53.1 44.2 55.5 Q46.5 57.9 48.8 55.5 Q51.1 53.1 53.4 55.5 Q54.5 57.9 55.6 55.5\" stroke=\"var(--accent)\" stroke-width=\"3.4\" fill=\"none\" stroke-linecap=\"round\"/><path d=\"M61.2 55.5 Q63.5 53.1 65.8 55.5 Q67.7 57.9 69.6 55.5\" stroke=\"var(--accent)\" stroke-width=\"3.4\" fill=\"none\" stroke-linecap=\"round\"/></svg>";

/** The mark at a given size, for a host that wants it larger than the default. */
export function renderMark(size = 24) {
  const px = Number.isFinite(size) && size > 0 ? Math.round(size) : 24;
  return MARK_MIN_SVG.replace('width="24" height="24"', `width="${px}" height="${px}"`);
}
