const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('ikmal', {
  platform: process.platform,
  getServiceState: () => ipcRenderer.invoke('service-state'),
  startServices: () => ipcRenderer.invoke('start-services'),
  stopServices: () => ipcRenderer.invoke('stop-services'),
  openEditor: (text) => ipcRenderer.invoke('open-editor', text || ''),
  openCompact: () => ipcRenderer.invoke('open-compact'),
  setCompactExpanded: (expanded) => ipcRenderer.invoke('set-compact-expanded', Boolean(expanded)),
  setCompactHeight: (height) => ipcRenderer.invoke('set-compact-height', Number(height)),
  getIntegrationStatus: () => ipcRenderer.invoke('integration-status'),
  getQualityStatus: () => ipcRenderer.invoke('quality-status'),
  installQualityStack: (acknowledged) => ipcRenderer.invoke('quality-setup', acknowledged === true),
  openThirdPartyNotices: () => ipcRenderer.invoke('open-third-party-notices'),
  revealExtension: () => ipcRenderer.invoke('reveal-extension'),
  configureIntegrations: (targetIDs) => ipcRenderer.invoke('configure-integrations', targetIDs),
  checkText: (text) => ipcRenderer.invoke('check-text', text),
  getRecentChecks: () => ipcRenderer.invoke('recent-checks'),
  clearRecentChecks: () => ipcRenderer.invoke('clear-recent-checks'),
  getStyleGuideState: () => ipcRenderer.invoke('style-guide-state'),
  importStyleGuide: () => ipcRenderer.invoke('import-style-guide'),
  selectStyleGuide: (id) => ipcRenderer.invoke('style-guide-select', id),
  setStyleGuideEnabled: (enabled) => ipcRenderer.invoke('style-guide-enabled', enabled),
  getLaunchAtLogin: () => ipcRenderer.invoke('get-launch-at-login'),
  setLaunchAtLogin: (enabled) => ipcRenderer.invoke('set-launch-at-login', enabled),
  getDesktopPresence: () => ipcRenderer.invoke('desktop-presence-state'),
  setDesktopPresence: (settings) => ipcRenderer.invoke('set-desktop-presence', settings),
  getAnnotationPreferences: () => ipcRenderer.invoke('get-annotation-preferences'),
  setAnnotationPreferences: (settings) => ipcRenderer.invoke('set-annotation-preferences', settings),
  getCheckingPreferences: () => ipcRenderer.invoke('get-checking-preferences'),
  setCheckingPreferences: (settings) => ipcRenderer.invoke('set-checking-preferences', settings),
  getSpellServerState: () => ipcRenderer.invoke('spell-server-state'),
  installSpellServer: () => ipcRenderer.invoke('install-spell-server'),
  removeSpellServer: () => ipcRenderer.invoke('remove-spell-server'),
  getOfficeBridgeState: () => ipcRenderer.invoke('office-bridge-state'),
  generateOfficeCertificate: () => ipcRenderer.invoke('office-bridge-generate-certificate'),
  startOfficeBridge: () => ipcRenderer.invoke('office-bridge-start'),
  stopOfficeBridge: () => ipcRenderer.invoke('office-bridge-stop'),
  removeOfficeCertificate: () => ipcRenderer.invoke('office-bridge-remove-certificate'),
  revealOfficeManifest: () => ipcRenderer.invoke('office-reveal-manifest'),
  revealOfficeExcelManifest: () => ipcRenderer.invoke('office-reveal-excel-manifest'),
  revealOfficePowerPointManifest: () => ipcRenderer.invoke('office-reveal-powerpoint-manifest'),
  revealOfficeOutlookManifest: () => ipcRenderer.invoke('office-reveal-outlook-manifest'),
  revealOfficeOneNoteManifest: () => ipcRenderer.invoke('office-reveal-onenote-manifest'),
  revealOfficeProjectManifest: () => ipcRenderer.invoke('office-reveal-project-manifest'),
  onServiceState: (callback) => ipcRenderer.on('service-state', (_, state) => callback(state)),
  onServiceError: (callback) => ipcRenderer.on('service-error', (_, message) => callback(message)),
  onQuickCheck: (callback) => ipcRenderer.on('quick-check', (_, text) => callback(text)),
  onCompactInvoked: (callback) => ipcRenderer.on('compact-invoked', () => callback()),
  onShowHistory: (callback) => ipcRenderer.on('show-history', () => callback()),
  onAnnotationPreferences: (callback) => ipcRenderer.on('annotation-preferences', (_, settings) => callback(settings)),
  onCheckingPreferences: (callback) => ipcRenderer.on('checking-preferences', (_, settings) => callback(settings)),
  onEditorText: (callback) => ipcRenderer.on('editor-text', (_, text) => callback(text)),
});
